### ISSUE TITLE
[MSVC2015]  'WM_PLUS_PRODUCT_ID': undeclared identifier

### ISSUE THREAD

**Issue by cboulay** [wiiuse/wiiuse#86]
Using Windows 10, following the instructions in the README, I am unable to build wiiuse library in any configuration.

cmake goes reasonably well, with warnings about missing SDL and GLUT.

Building the library in MSVC 2015 Community, Debug or Release configuration, fails with the following error:

`wiiuse\src\os_win.c(123): error C2065: 'WM_PLUS_PRODUCT_ID': undeclared identifier`

Searching the repository on GitHub reveals that this comes up only in the [offending line](https://github.com/rpavlik/wiiuse/blob/master/src/os_win.c#L123-L124) and in a issue #58 comment. The line was added with commit d5dc22c108e6b60a85e82627cca267e01a35d6af and merged with #61 in April 2015.

It would be very surprising to me if something that breaks all Windows builds has been in master for over a year. Maybe the declaration of `WM_PLUS_PRODUCT_ID` was removed recently? Or am I missing something?

**Comment by cboulay** [comment]
I just tried the 'updates' branch and that worked fine. I'll try to merge the branch, fix conflicts, then create a pull request.

**Comment by janoc** [comment]
I was just going to say that there were likely crossing merges, breaking the master :(
@rpavlik  has a staging branch "updates" where some of these things were fixed already - e.g. the WM_PLUS_PRODUCT_ID is defined there.

I will try to ping Ryan (@rpavlik) about merging "updates" because there are many things he had in progress there.

**Comment by qwertychouskie** [comment]
This bug was introduced with the merging of https://github.com/rpavlik/wiiuse/pull/58.  Apparently https://github.com/rpavlik/wiiuse/blob/master/src/os_win.c#L123 was not updated with the new variable name.  If @cboulay could make a separate PR of just https://github.com/cboulay/wiiuse/commit/68bbafb3f7b56a29763a9f4820e2d06ce150d2da, that would fix the problem.

**Comment by janoc** [comment]
@rpavlik told me earlier that he will look at the merging. Patience, please :)

**Comment by oblitum** [comment]
bump

**Comment by cdekkers** [comment]
I am running into this issue as well. Can anyone help me solving it?

**Comment by janoc** [comment]
Try to update, I have committed a fix.

**Comment by cdekkers** [comment]
This seems to have fixed my issue. Thanks for the swift reply.
